# Generated by Django 5.2.9 on 2025-12-10 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('role', models.CharField(choices=[('employee', 'Employee'), ('manager', 'Manager'), ('hradmin', 'HR Admin')], max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('department_id', models.IntegerField()),
                ('designation', models.CharField(max_length=100)),
                ('designation_id', models.IntegerField()),
                ('position', models.CharField(max_length=100)),
                ('grade', models.IntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4')])),
                ('skills', models.TextField(help_text="Comma-separated skill IDs (e.g., '8,15,3')")),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('on_leave', 'On Leave')], default='active', max_length=20)),
                ('hire_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employees',
                'ordering': ['employee_id'],
                'managed': False,
            },
        ),
    ]
